export const WORKSPACE_DELETION_LOCK_TIMEOUT_MS = 500;
export const WORKSPACE_DELETION_STATEMENT_TIMEOUT_MS = 5_000;
export const WORKSPACE_DELETION_CLIENT_TIMEOUT_MS = 8_000;
export const WORKSPACE_DELETION_PHASE_TIMEOUT_MS = 15_000;
export const WORKSPACE_DELETION_JOB_TIMEOUT_MS = 2 * 60_000;
