export const WORKSPACE_DELETION_LOCK_TIMEOUT_MS = 500;
export const WORKSPACE_DELETION_STATEMENT_TIMEOUT_MS = 90_000;
export const WORKSPACE_DELETION_CLIENT_TIMEOUT_MS = 95_000;
export const WORKSPACE_DELETION_PHASE_TIMEOUT_MS = 110_000;
export const WORKSPACE_DELETION_JOB_TIMEOUT_MS = 2 * 60_000;
export const WORKSPACE_DELETION_OPERATIONAL_STALE_AFTER_MS =
  WORKSPACE_DELETION_JOB_TIMEOUT_MS;
export const WORKSPACE_DELETION_OPERATIONAL_MAX_AGE_MS = 20 * 60_000;
