import { type FlatWorkspace } from 'src/engine/core-modules/workspace/types/flat-workspace.type';
import { type WorkspaceEntity } from 'src/engine/core-modules/workspace/workspace.entity';

export const fromWorkspaceEntityToFlat = (
  entity: WorkspaceEntity,
): FlatWorkspace => ({
  id: entity.id,
  displayName: entity.displayName,
  logo: entity.logo,
  logoFileId: entity.logoFileId,
  inviteHash: entity.inviteHash,
  allowImpersonation: entity.allowImpersonation,
  isPublicInviteLinkEnabled: entity.isPublicInviteLinkEnabled,
  workspaceDiscoverability: entity.workspaceDiscoverability,
  trashRetentionDays: entity.trashRetentionDays,
  eventLogRetentionDays: entity.eventLogRetentionDays,
  activationStatus: entity.activationStatus,
  deletionKind: entity.deletionKind,
  deletionPhase: entity.deletionPhase,
  deletionRequestedAt: entity.deletionRequestedAt?.toISOString() ?? null,
  deletionLastProgressAt: entity.deletionLastProgressAt?.toISOString() ?? null,
  deletionAttemptCount: entity.deletionAttemptCount,
  deletionLastErrorCode: entity.deletionLastErrorCode,
  deletionLastErrorMessage: entity.deletionLastErrorMessage,
  metadataVersion: entity.metadataVersion,
  databaseSchema: entity.databaseSchema,
  subdomain: entity.subdomain,
  customDomain: entity.customDomain,
  isGoogleAuthEnabled: entity.isGoogleAuthEnabled,
  isGoogleAuthBypassEnabled: entity.isGoogleAuthBypassEnabled,
  isTwoFactorAuthenticationEnforced: entity.isTwoFactorAuthenticationEnforced,
  isPasswordAuthEnabled: entity.isPasswordAuthEnabled,
  isPasswordAuthBypassEnabled: entity.isPasswordAuthBypassEnabled,
  isMicrosoftAuthEnabled: entity.isMicrosoftAuthEnabled,
  isMicrosoftAuthBypassEnabled: entity.isMicrosoftAuthBypassEnabled,
  isCustomDomainEnabled: entity.isCustomDomainEnabled,
  editableProfileFields: entity.editableProfileFields,
  defaultRoleId: entity.defaultRoleId,
  fastModel: entity.fastModel,
  smartModel: entity.smartModel,
  aiAdditionalInstructions: entity.aiAdditionalInstructions,
  enabledAiModelIds: entity.enabledAiModelIds,
  useRecommendedModels: entity.useRecommendedModels,
  isInternalMessagesImportEnabled: entity.isInternalMessagesImportEnabled,
  workspaceCustomApplicationId: entity.workspaceCustomApplicationId,
  routerModel: entity.routerModel,
  createdAt: entity.createdAt.toISOString(),
  updatedAt: entity.updatedAt.toISOString(),
  deletedAt: entity.deletedAt?.toISOString(),
  suspendedAt: entity.suspendedAt?.toISOString() ?? null,
});
