export enum MetadataSideEffectExceptionCode {
  RESERVED_SYSTEM_UNIVERSAL_IDENTIFIER = 'RESERVED_SYSTEM_UNIVERSAL_IDENTIFIER',
  SIDE_EFFECT_PARENT_METADATA_NOT_FOUND = 'SIDE_EFFECT_PARENT_METADATA_NOT_FOUND',
  REGIE_CUSTOM_FIELD_MARKER_INVALID = 'REGIE_CUSTOM_FIELD_MARKER_INVALID',
  REGIE_CUSTOM_FIELD_SEARCH_UNAVAILABLE = 'REGIE_CUSTOM_FIELD_SEARCH_UNAVAILABLE',
  REGIE_CUSTOM_FIELD_TARGET_MISMATCH = 'REGIE_CUSTOM_FIELD_TARGET_MISMATCH',
}
