export enum MetadataSideEffectExceptionCode {
  RESERVED_SYSTEM_UNIVERSAL_IDENTIFIER = 'RESERVED_SYSTEM_UNIVERSAL_IDENTIFIER',
  SIDE_EFFECT_PARENT_METADATA_NOT_FOUND = 'SIDE_EFFECT_PARENT_METADATA_NOT_FOUND',
  ADDITIONAL_SEARCH_REGISTRATION_FAILED = 'ADDITIONAL_SEARCH_REGISTRATION_FAILED',
}
